version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: aws-sdk
    versions:
    - 2.831.0
    - 2.853.0
    - 2.884.0
  - dependency-name: ssri
    versions:
    - 8.0.1
  - dependency-name: npm-check-updates
    versions:
    - 11.0.2
    - 11.1.1
    - 11.1.10
    - 11.1.4
    - 11.1.9
    - 11.2.0
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.2
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.8
  commit-message:
    prefix: chore
    include: scope
