version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    docker:
      - image: circleci/node:12

    working_directory: ~/repo

    steps:
      - checkout

      - run: npm ci

      - run: git fetch --tags
      # - run: npx commitlint --from $(git describe --abbrev=0 --tags)

      - run: npm test

      - codecov/upload:
          file: coverage/lcov.info

      - persist_to_workspace:
          root: ~/repo
          paths: .
  publish:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Discable strict ssh key checking
          command: mkdir -p ~/.ssh && echo -e "Host github.com\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile /dev/null\n" > ~/.ssh/config
      - run:
          name: Publish package
          command: |
            last_commit="$(git log -1 --pretty=%B | cat | grep 'chore(release)')" || true
            if [[ ${last_commit} == *[chore\(release\)]* ]]
            then echo "last commit was release, skipping semantic release step"
            else npm run release
            fi

workflows:
  version: 2
  build-publish:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
      - publish:
          requires:
            - build
          filters:
            tags:
              ignore: /.*/
            branches:
              only:
                - master
                - beta
                - alpha
